apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: StackId-health-check-task
  namespace: kabanero
spec:
  inputs:
    params:
      - default: googlefu/apic_compiler:v3-amd64
        name: tools-image
        type: string
    resources:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - args:
        - -c
        - |
          set -e

          apt-get install -y jq curl
          oc whoami

          # get routes and create a json file
          oc get routes -n qa -o json > routes.json

          # look in the json file and get the web url
          qa_route=$(jq '.items | .[0].spec.host' ./routes.json)
          temp=$(echo $qa_route | tr -d '"')
          echo $temp
          curl "http://${temp}/_healthchecks" > health-endpoint.json

          cat health-endpoint.json

          # check if there are any failed key value pairs


          did_health_status_failed=$(jq '.["failed"] == []' ./health-endpoint.json)

          if [ "$did_health_status_failed" = "true" ]; then
            echo Health Status OK
          else
            echo ERROR: There was a problem in the health status, please check the health-endpoint.json file
            exit 1
          fi

      command:
        - /bin/bash
      image: $(inputs.params.tools-image)
      name: health-check
      resources: {}
      workingDir: $(inputs.resources.source.path)
